-- api_ip_allowlist: server IPs a merchant has told us their API traffic
-- comes from — Infinity never generates these, merchants provide their own
-- (see docs). Enforcement only ever applies to `live` environment traffic
-- (see app/auth/dependencies.py::verify_api_key) — a merchant testing
-- against sandbox is never IP-restricted, and enforcement itself is
-- opt-in: a merchant with zero *active* allowlist rows for `live` is
-- unrestricted (an empty allowlist is not a lockout), matching "if IP
-- allowlist is enabled for a production key" in the task brief — "enabled"
-- here means "has at least one active row", not a separate toggle.

create table public.api_ip_allowlist (
  id uuid primary key default gen_random_uuid(),

  merchant_id uuid not null references public.merchants (id) on delete cascade,
  api_key_id uuid references public.api_keys (id) on delete set null,

  environment text not null check (environment in ('sandbox', 'live')),
  label text not null,
  ip_address_or_cidr text not null,

  status text not null default 'pending' check (status in ('pending', 'active', 'rejected')),
  notes text,

  created_by uuid references auth.users (id) on delete set null,
  approved_by uuid references auth.users (id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.api_ip_allowlist is
  'Merchant-provided server IPs/CIDRs their API traffic is expected from — never generated by Infinity. Only enforced for live-environment requests, and only once a merchant has at least one active row.';
comment on column public.api_ip_allowlist.api_key_id is
  'Optional: scope this entry to one specific API key rather than every key on the merchant. Null = applies to all of the merchant''s keys in this environment.';

create index api_ip_allowlist_merchant_id_idx on public.api_ip_allowlist (merchant_id);
create index api_ip_allowlist_status_idx on public.api_ip_allowlist (status);

create trigger api_ip_allowlist_set_updated_at
  before update on public.api_ip_allowlist
  for each row execute function public.set_updated_at();

alter table public.api_ip_allowlist enable row level security;
